# Generated by Django 3.1 on 2021-07-19 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0002_auto_20210719_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderformmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderformmodel',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
