# Generated by Django 3.1 on 2021-07-19 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0003_auto_20210720_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderformmodel',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
