# Generated by Django 3.1 on 2021-07-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0004_auto_20210720_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCust1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('custType', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=200)),
                ('note', models.TextField(max_length=100)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pstore.photostoremodel')),
            ],
        ),
    ]
