# Generated by Django 3.1 on 2021-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstore', '0006_auto_20210720_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcust1model',
            name='note',
            field=models.CharField(max_length=100),
        ),
    ]
