# Generated by Django 3.1 on 2021-07-20 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pstore', '0007_auto_20210720_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcust1model',
            name='order_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
